name: Prevedi zbirko
on:
  push:
    branches:
      - master
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Kloniraj git repozitorij
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Dodaj povezavo do paketa omrezja
        run: |
          cd $GITHUB_WORKSPACE
          ln -s omrezja/omrezja.sty
      - name: Prevedi zbirko
        uses: xu-cheng/latex-action@master
        with:
          root_file: or-zbirka.tex
      - name: Premakni PDF
        run: |
          mkdir pdf
          mv or-zbirka.pdf pdf/
      - name: Nalo≈æi PDF
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: pdf
